Enhancement/adding lambdas for async callable class
animo93/JRest pull request #40
Opened 2024-10-16 09:44 UTC by 3looy-hubs

#36

2024-10-16 21:18 UTC, animo93 requested changes
Apart from the comments , below two changes can also be made :- 

1. The `APICallBack` interface can be redesigned to use `Consumer` in both it's methods . 
2. And test case for `callMeLater` can be added to all the existing test cases like `DynamicInvocationTest` , `HeaderTest` , `QueryParamTest` and `RequestBodyTest`

2024-10-16 21:18 UTC, animo93 commented on src/main/java/com/animo/jRest/exception/IThrowingFunction.java
I don't feel that we need to create a `Functional Interface` just to implement a exception throwing `Function` . The `callmeNow` function can be kept as it is since it's anyway making a blocking call

2024-10-16 21:18 UTC, animo93 commented on src/main/java/com/animo/jRest/util/APICall.java
> +        return asyncTask.executeNow.apply(requestBean);
No need for this change . Let's keep it as it is

2024-10-16 21:18 UTC, animo93 commented on src/main/java/com/animo/jRest/util/AsyncTask.java
> +    IThrowingFunction<Params, Result> executeNow = (params) -> {
No need to make any changes to this function . Let's keep it as it is

2024-10-16 21:18 UTC, animo93 commented on src/test/java/com/animo/jRest/test/AsyncCallableTest.java
This Test can be removed , because we are anyway doing IT test directly with get-postman API

2024-10-17 06:09 UTC, 3looy-hubs commented
Alright well do

2024-10-17 09:03 UTC, 3looy-hubs commented
I couldnt figure it out I need help

2024-10-17 18:35 UTC, animo93 approved these changes
I am accepting this for now . But the entire `callmeLater` method needs to be re-designed using `CompletableFuture` , for which i will create a separate issue

2024-10-17 18:36 UTC, merged